spring:
  application:
    name: Enjoying

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/Airbnb
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


server:
  error:
    include-stacktrace: always

app:
  jwt:
    secret: nurislam&java12